language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: "./build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
    secure: DIP21FRb/6yMTkaRu7kfEHQrQl6hVfu1u3q1WRi4/bKmcWWNmzEU8ibHHp/rrRrdgCcfBep+hlN0HEtXPIngK6a4Is/26tAx3P4qsoUXP6LVb/FI62rIAGvVmr/g6gVq/b2foApQvAxUYm+Fu49TipQVqdDTcMM6mLDRaz0U7GmWKgTyuPvap+4UFmKbVudxzBOXPU0DPEW9jPjBoVhYX76/IPbKH8pkli3nO0mHFfPHhwi4JPJiC4PJr3lJn6K7WdiVCI/XbI75Ayi345zywX7kGsYlUx3v2BmR8xTN4KsdDnp1k5Orzk7aR8qnFJc2e3YFSEsC9H4fQ9gmwg12VpWXlHxDCNbLCv1ZwS4DKlUECac2wN7nZViSHZbMJ3A9w91OQjXLw6ComMwGqFvAzyNyEhnOkjev0s4BkYmiBZrHhYr13j1aji+AMUXd0QqT32hONdjR/PzEEdVMMnoaDbGqN+EYFXAA3rALCuS1gRCY3wsCV03BKH6V7NkDd0xCK8Lizj4LJrZqluQ6RpRlguDmG6HvsS8jfBrF/FdqxqInVNqTS4ybvszk4Q7LOiRg9qbl/naYqNNsXz7YNP6Fltu0WkeMgrvXZAv6H+Ejv+LK7eDK24FaFoDBr8E4Iw+GaRKmG+Tj4SIZ8QQ9Vr+Dbm2jmrzkG4XlKM88mE1cTZI=
